version: '3.8'

services:
  frontend:
    image: my-react-app  # ✅ Ensure `image` is a string
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2  # ✅ Corrected `depends_on` syntax

  backend1:
    image: my-python-api-app  # ✅ Ensure `image` is a string
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    depends_on:
      - mysql  # ✅ Corrected `depends_on` indentation

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  mysql:
    container_name: mysql_db
    image: my-mysql-db  # ✅ Ensure `image` is a string
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: nandhu01
      MYSQL_DATABASE: resume_analyzer
    ports:
      - "3308:3306"
