FROM debian:bullseye

# Install the default MySQL client package
RUN apt-get update && apt-get install -y default-mysql-client

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=nandhu01
ENV MYSQL_DATABASE=resume_analyzer

# Expose MySQL port
EXPOSE 3306
