# Dockerfile for server.py (Backend 2)

FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend code for server.py
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirments.txt
# Copy the server.py file into the container
COPY server.py /app/

# Expose the port that the application will run on
EXPOSE 5001

# Set the entry point to run the server.py when the container starts
CMD ["python", "server.py"]

