# Use Python official image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirments.txt .
RUN pip install -r requirments.txt

# Copy application code
COPY . .

# Expose the port that the server will run on
EXPOSE 5001

# Command to run the backend server with gunicorn (or uvicorn for ASGI apps)
CMD ["gunicorn", "-b", "0.0.0.0:5001", "server:app"]
